### ISSUE TITLE
maken van een progress bar tijdens het lezen van een artikel

### ISSUE THREAD

**Issue by SamaraFellaDina** [SamaraFellaDina/pleasurable-ui#19]

**Comment by SamaraFellaDina** [comment]
ff shoutout naar [christoph3r3w](https://github.com/christoph3r3w/pleasurable-ui/blob/main/public/styles/detail.css#L5-L18) zijn code :) Zo maak je de progress bar.

```css
body::after{
	content: '';
	height:7px ;
	position: fixed;
	top: 0;
	z-index: 100;
	background-color: #e7432d;
	width: 100%;
	scale: 0 1;
	transform-origin: left;


	animation: scroll linear;
	animation-timeline: scroll(y) ;
}

@keyframes scroll {
	to{scale: 1 1;}
}

```
