### ISSUE TITLE
Het maken van `code conventies`

### ISSUE THREAD

**Issue by SamaraFellaDina** [SamaraFellaDina/pleasurable-ui#8]
# Code conventies

## `html`
* Zo min mogelijk `div` gebruiken
* Goede semantische objecten gebruiken
* Wanneer je `ejs` objecten gebruikt dat er een spatie zit tussen de ejs benamingen.
```html
<%- article.rendered.image %>
```
## `css`
* Maak de css code `DRY`. Dus eerst de basiselementen stijlen, waarna je de classes stijlt
* Werk `mobile-first` !!!
* Wanneer je meerdere objecten aanroept, er een enter tussen elk object komt 
```css
p,
ul,
li,
button {
    font-family: var(--font-sans-serif);
    font-size: 1.1em;
    line-height: 1.5em;
}
```
* Wanneer je gebruik maakt van een `@media-query` gebruikt, de waarde binnen het object zet en niet onderaan het bestand. 
Zo moet je het dus niet doen.

https://github.com/SamaraFellaDina/pleasurable-ui/blob/83b0d5311269e8d1128cffbc9cd704a81ab2b71a/public/style.css#L227-L238

maar zo: 

```css
header {
    background-color: var(--primary-color-3);
    border-bottom: var(--border-style-black);
    width: 100%;

  @media (min-width: 768px) {
        border-bottom: none;
}
```
### Naamgeving
* Wanneer je een class aanroept, geeft de volgende naamgeving. 
* Maak gebruik van de `BEM` methode. Hierbij geef je de code de volgende naamgeving:
  * Je doet dus `onderwerp` + `object`
```css
.stickman-head
```
  
## `JavaScript`
* naamgeving: Maak gebruik van `CamelCase`
### Commits
* Wanneer je met een issue bezig bent, noem de issue in de titel. Benoem deze nog niet als `fix`, dit is handiger in de `pull-request` message.
* Geef de titel een goede uitleg die samenvat wat je allemaal hebt gedaan
* Hou commits klein! Kleine taken en deze per taak commiten
### Branch
* Naamgeving: Wanneer je aan een specifieke feature werkt, geef je de volgende naamgeving aan een branch. `Feature` + `onderwerp` + `eigen naam`. Dus bijvoorbeeld `feature-header-sammy`
* Wanneer je een nieuwe branch wilt aanmaken, doe dit via GitHub. Dit is handiger, omdat je het anders eerst moet pushen. Dus doe dit direct via de website i.p.v GitHub Desktop
### Pull request
* Wanneer je een pull request maakt, benoem de volgende dingen:
  * Alle aanpassingen die je hebt gemaakt
  * Wat er gecontroleerd moet worden
  * De mensen taggen die naar de request moeten kijken
* Als je aan bepaalde issues hebt gewerkt in deze request, zet deze dan neer met een `fix`, zodat deze meteen wordt afgevinkt in het project board
